# Generated by Django 4.2 on 2025-10-16 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id_tipo_categoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'TipoCategoria',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='categories.tipocategoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='users.usuario')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['usuario', 'tipo_categoria', 'nombre'], name='ix_cat_usu_tipo_nom'),
        ),
    ]
