# Generated by Django 5.2.7 on 2025-10-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
