# Generated by Django 5.2.7 on 2025-10-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoria_monto'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoria',
            name='ix_cat_usu_tipo_nom',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
    ]
