# Generated by Django 5.2.7 on 2025-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categoriusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=150),
        ),
        migrations.DeleteModel(
            name='TipoCategoria',
        ),
    ]
