# Generated by Django 5.2.7 on 2025-10-21 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_categoria_tipo_categoria_delete_tipocategoria'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriusuario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.categoria'),
        ),
        migrations.AlterField(
            model_name='categoriusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
