# Generated by Django 5.2.7 on 2025-10-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categoriusuario_categoria_and_more'),
        ('frequency', '0004_alter_frecuenciafija_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='frecuencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frequency.frecuencia'),
        ),
        migrations.AddField(
            model_name='categoriusuario',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='categoriusuario',
            table='CategoriUsuario',
        ),
    ]
