# Generated by Django 5.2.7 on 2025-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_categoria_frecuencia_categoriusuario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Ingreso Fijo', 'Ingreso Fijo'), ('Gasto Fijo', 'Gasto Fijo')], max_length=150),
        ),
    ]
