# Generated by Django 5.2.7 on 2025-10-30 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_categoria_frecuencia_categoriusuario_fecha_and_more'),
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriusuario',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea.tarea'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Ingreso Fijo', 'Ingreso Fijo'), ('Gasto Fijo', 'Gasto Fijo')], max_length=150),
        ),
    ]
