# Generated by Django 5.2.7 on 2025-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_categoriusuario_tarea_alter_categoria_tipo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Ingreso_Fijo', 'Ingreso_Fijo'), ('Gasto_Fijo', 'Gasto_Fijo')], max_length=150),
        ),
    ]
