# Generated by Django 5.2.7 on 2025-11-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_categoria_tipo_categoria'),
        ('categories', '0009_alter_categoria_tipo_categoria'),
    ]

    operations = [
    ]
