# Generated by Django 5.2.7 on 2025-10-25 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequency', '0003_frecuenciafija'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoFijo',
            fields=[
                ('id_ingreso_fijo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Sueldo', max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('dia_corte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('es_principal', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='frequency.frecuencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_fijos', to='users.usuario')),
            ],
            options={
                'db_table': 'Ingreso_fijo',
                'indexes': [models.Index(fields=['usuario', 'activo'], name='Ingreso_fij_usuario_7af5c5_idx')],
            },
        ),
    ]
