# Generated by Django 4.2 on 2025-09-22 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('periodoid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'Periodo',
            },
        ),
        migrations.AddIndex(
            model_name='periodo',
            index=models.Index(fields=['anio', 'mes'], name='idx_periodo_aniomes'),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('anio', 'mes')},
        ),
    ]
