# Generated by Django 4.2 on 2025-10-16 03:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='periodoid',
        ),
        migrations.AddField(
            model_name='periodo',
            name='id_periodo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='mes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
