# Generated by Django 5.2.7 on 2025-10-30 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaProgramada', models.DateField(blank=True, null=True)),
                ('fechaEjecutada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'Tarea',
            },
        ),
    ]
