# Generated by Django 5.2.7 on 2025-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado')], default='Pendiente', max_length=200, null=True),
        ),
    ]
