# Generated by Django 4.2 on 2025-09-11 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('Frecuencia', models.CharField(blank=True, choices=[('D', 'Diario'), ('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual'), ('B', 'Bimestral'), ('T', 'Trimestral')], max_length=200, null=True)),
            ],
        ),
    ]
