# Generated by Django 4.2 on 2025-10-16 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frecuencia',
            name='Frecuencia',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='id',
        ),
        migrations.AddField(
            model_name='frecuencia',
            name='id_frecuencia',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='descripcion',
            field=models.CharField(default='UNSET', max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='frecuencia',
            table='Frecuencia',
        ),
    ]
