# Generated by Django 5.2.7 on 2025-10-25 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0002_remove_frecuencia_frecuencia_remove_frecuencia_id_and_more'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrecuenciaFija',
            fields=[
                ('id_frecuencia_fija', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_frecuencia_fija', to='frequency.frecuencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frecuencia_fija', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Frecuencia fija',
                'verbose_name_plural': 'Frecuencias fijas',
                'db_table': 'Frecuencia_fija',
            },
        ),
    ]
