# Generated by Django 5.2.7 on 2025-10-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0003_frecuenciafija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuenciafija',
            name='frecuencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_frecuencia_fija', to='frequency.frecuencia'),
        ),
    ]
