# Generated by Django 4.2 on 2025-10-19 05:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
        ('period', '0002_remove_periodo_periodoid_periodo_id_periodo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_transaccion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='categories.categoria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='period.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='users.usuario')),
            ],
            options={
                'db_table': 'Transaccion',
            },
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['usuario', 'periodo'], name='ix_trans_usuario_periodo'),
        ),
    ]
