# Generated by Django 4.2 on 2025-10-18 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0002_remove_periodo_periodoid_periodo_id_periodo_and_more'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasignacionPresupuestal',
            fields=[
                ('id_reasignacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salientes', to='categories.categoria')),
                ('categoria_hacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrantes', to='categories.categoria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones', to='period.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones', to='users.usuario')),
            ],
            options={
                'db_table': 'ReasignacionPresupuestal',
            },
        ),
    ]
