# Generated by Django 4.2 on 2025-10-16 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id_credencial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_login', models.EmailField(max_length=150, unique=True)),
                ('hash_password', models.BinaryField(max_length=512)),
                ('salt', models.BinaryField(max_length=128)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='users.usuario')),
            ],
            options={
                'db_table': 'Credencial',
            },
        ),
    ]
