# Generated by Django 5.2.7 on 2025-10-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-fecha_registro']},
        ),
    ]
