# Generated by Django 5.2.7 on 2025-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='hash_password',
            field=models.CharField(max_length=512),
        ),
    ]
