# Generated by Django 5.2.7 on 2025-11-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_credencial_hash_password'),
        ('users', '0005_passwordresetcode'),
    ]

    operations = [
    ]
