# Generated by Django 4.2 on 2025-10-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0002_remove_periodo_periodoid_periodo_id_periodo_and_more'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PRE', 'Pre'), ('POST', 'Post')], max_length=10)),
                ('fuente', models.CharField(choices=[('DECLARADA', 'Declarada'), ('CALCULADA', 'Calculada')], max_length=15)),
                ('capturado_en', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='period.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='users.usuario')),
            ],
            options={
                'db_table': 'Evaluacion',
                'unique_together': {('usuario', 'periodo', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id_metrica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Metrica',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionMetrica',
            fields=[
                ('id_eval_metrica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_numerico', models.DecimalField(decimal_places=4, max_digits=18)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='evaluations.evaluacion')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluations.metrica')),
            ],
            options={
                'db_table': 'EvaluacionMetrica',
                'unique_together': {('evaluacion', 'metrica')},
            },
        ),
    ]
