# Generated by Django 4.2 on 2025-10-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0002_remove_periodo_periodoid_periodo_id_periodo_and_more'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionGasto',
            fields=[
                ('id_programacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_planificada', models.DateField()),
                ('realizado_en_fecha', models.BooleanField(blank=True, null=True)),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='categories.categoria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='period.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='users.usuario')),
            ],
            options={
                'db_table': 'ProgramacionGasto',
            },
        ),
    ]
