# Generated by Django 4.2 on 2025-10-18 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequency', '0002_remove_frecuencia_frecuencia_remove_frecuencia_id_and_more'),
        ('period', '0002_remove_periodo_periodoid_periodo_id_periodo_and_more'),
        ('categories', '0001_initial'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frequency.frecuencia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='period.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='users.usuario')),
            ],
            options={
                'db_table': 'Presupuesto',
                'unique_together': {('usuario', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id_item', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_planificado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_presupuesto', to='categories.categoria')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.presupuesto')),
            ],
            options={
                'db_table': 'PresupuestoItem',
            },
        ),
    ]
