# Generated by Django 5.2.7 on 2025-11-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcentajeEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoEjecutado', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('montoPlanificado', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'PorcentajeEjecucion',
            },
        ),
    ]
