# Generated by Django 5.2.7 on 2025-11-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
        ('users', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ajustesPresupuestales', models.IntegerField(blank=True, null=True)),
                ('tareasRealizadasEnFecha', models.IntegerField(blank=True, null=True)),
                ('totalTareasProgramadas', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'ControlConsumo',
            },
        ),
    ]
