# Generated by Django 4.2 on 2025-10-18 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('monto_meta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('CUMPLIDO', 'Cumplido'), ('CANCELADO', 'Cancelado')], default='EN_PROGRESO', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='users.usuario')),
            ],
            options={
                'db_table': 'Objetivo',
            },
        ),
    ]
