# Generated by Django 5.2.7 on 2025-10-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='horizonte',
            field=models.IntegerField(blank=True, null=True, verbose_name='horizonte(meses)'),
        ),
    ]
