# Generated by Django 5.2.7 on 2025-10-26 07:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_objetivo_horizonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleObjetivo',
            fields=[
                ('idDetObjt', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DetalleObjetivo',
            },
        ),
    ]
