# Generated by Django 4.2 on 2025-10-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id_regla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='users.usuario')),
            ],
            options={
                'db_table': 'Regla',
            },
        ),
        migrations.CreateModel(
            name='ReglaDetalle',
            fields=[
                ('id_regla_detalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=80)),
                ('valor', models.CharField(max_length=120)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rules.regla')),
            ],
            options={
                'db_table': 'ReglaDetalle',
            },
        ),
    ]
