# Generated by Django 5.2.7 on 2025-10-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('users', '0002_usuario_activo_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regla',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='regladetalle',
            name='parametro',
        ),
        migrations.AddField(
            model_name='regladetalle',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regladetalle',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regladetalle',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='regladetalle',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
