# Generated by Django 5.2.7 on 2025-10-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_remove_regla_usuario_remove_regladetalle_parametro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladetalle',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, null=True),
        ),
    ]
